import type { DataRow } from "../types";

export interface Showcase {
  id: string;
  role: string;
  title: string;
  summary: string;
  outcome: string;
  rows: DataRow[];
}
export const showcases: Showcase[] = [
  {
    id: "sales",
    role: "Business Analyst",
    title: "Sales & revenue review",
    summary: "Find revenue concentration, refunds, and regional performance.",
    outcome: "A board-ready commercial performance pack",
    rows: [
      {
        order_id: "SO-101",
        order_date: "2026-05-03",
        region: "North",
        channel: "Enterprise",
        revenue: 42000,
        refund: 0,
        currency: "INR",
        owner: "Aarav",
      },
      {
        order_id: "SO-102",
        order_date: "2026-05-08",
        region: "West",
        channel: "Partner",
        revenue: 28500,
        refund: 2500,
        currency: "INR",
        owner: "Diya",
      },
      {
        order_id: "SO-103",
        order_date: "2026-06-02",
        region: "South",
        channel: "Enterprise",
        revenue: 51000,
        refund: 0,
        currency: "INR",
        owner: "Meera",
      },
      {
        order_id: "SO-104",
        order_date: "2026-06-14",
        region: "West",
        channel: "Self-serve",
        revenue: 9800,
        refund: 1200,
        currency: "INR",
        owner: "Kabir",
      },
      {
        order_id: "SO-105",
        order_date: "2026-07-06",
        region: "North",
        channel: "Partner",
        revenue: 33500,
        refund: 0,
        currency: "INR",
        owner: "Aarav",
      },
      {
        order_id: "SO-106",
        order_date: "2026-07-17",
        region: "South",
        channel: "Enterprise",
        revenue: 87000,
        refund: 0,
        currency: "INR",
        owner: "Meera",
      },
      {
        order_id: "SO-107",
        order_date: "2026-08-04",
        region: "East",
        channel: "Self-serve",
        revenue: 11200,
        refund: 900,
        currency: "INR",
        owner: "Zoya",
      },
      {
        order_id: "SO-108",
        order_date: "2026-08-21",
        region: "West",
        channel: "Partner",
        revenue: 38200,
        refund: 0,
        currency: "INR",
        owner: "Diya",
      },
    ],
  },
  {
    id: "operations",
    role: "AI Automation Engineer",
    title: "Operations exception workflow",
    summary: "Triage SLA breaches and design an auditable escalation recipe.",
    outcome: "An automation-ready exception queue",
    rows: [
      {
        ticket_id: "OP-201",
        created_date: "2026-08-01",
        category: "Payment",
        status: "Resolved",
        resolution_hours: 3,
        owner: "Nina",
      },
      {
        ticket_id: "OP-202",
        created_date: "2026-08-01",
        category: "Fulfilment",
        status: "Escalated",
        resolution_hours: 31,
        owner: "Ravi",
      },
      {
        ticket_id: "OP-203",
        created_date: "2026-08-02",
        category: "Payment",
        status: "Open",
        resolution_hours: 48,
        owner: null,
      },
      {
        ticket_id: "OP-204",
        created_date: "2026-08-03",
        category: "Identity",
        status: "Resolved",
        resolution_hours: 7,
        owner: "Nina",
      },
      {
        ticket_id: "OP-205",
        created_date: "2026-08-04",
        category: "Fulfilment",
        status: "Escalated",
        resolution_hours: 72,
        owner: "Ravi",
      },
      {
        ticket_id: "OP-206",
        created_date: "2026-08-05",
        category: "Identity",
        status: "Open",
        resolution_hours: 19,
        owner: "Tara",
      },
    ],
  },
  {
    id: "founder",
    role: "Founder's Office",
    title: "Founder KPI & cash-flow pack",
    summary:
      "Separate cash balance, burn, and revenue without unsafe arithmetic.",
    outcome: "A concise operating review with next actions",
    rows: [
      {
        month: "2026-03-01",
        category: "Actual",
        revenue: 620000,
        expense: 790000,
        balance: 2450000,
        currency: "INR",
      },
      {
        month: "2026-04-01",
        category: "Actual",
        revenue: 715000,
        expense: 825000,
        balance: 2340000,
        currency: "INR",
      },
      {
        month: "2026-05-01",
        category: "Actual",
        revenue: 810000,
        expense: 860000,
        balance: 2290000,
        currency: "INR",
      },
      {
        month: "2026-06-01",
        category: "Actual",
        revenue: 940000,
        expense: 910000,
        balance: 2320000,
        currency: "INR",
      },
      {
        month: "2026-07-01",
        category: "Actual",
        revenue: 1080000,
        expense: 970000,
        balance: 2430000,
        currency: "INR",
      },
      {
        month: "2026-08-01",
        category: "Actual",
        revenue: 1210000,
        expense: 1040000,
        balance: 2600000,
        currency: "INR",
      },
    ],
  },
];
